<!-- @@author superkaiba -->

@startuml
!pragma teoz true
hide footbox

User -> BigPP : list [COMPONENT]
activate User
activate BigPP

BigPP -> Parser : parseCommand(String userInput)
activate Parser

Parser -> Parser : parseBuilderCommand(String userInput)
activate Parser
create BuilderListComponentCommand

Parser -> BuilderListComponentCommand : BuilderListComponentCommand(String arguments)
activate BuilderListComponentCommand
BuilderListComponentCommand --> Parser
deactivate BuilderListComponentCommand

deactivate Parser
Parser --> BigPP: BuilderListComponentCommand
deactivate Parser

BigPP -> BuilderListComponentCommand : executeCommand()
activate BuilderListComponentCommand
BuilderListComponentCommand -> DataStorage.stringToComponentListMap : get(String componentType)
activate DataStorage.stringToComponentListMap
DataStorage.stringToComponentListMap --> BuilderListComponentCommand : [COMPONENT_TYPE]List
deactivate DataStorage.stringToComponentListMap

BuilderListComponentCommand -> "[COMPONENT_TYPE]List" : getListString()
activate "[COMPONENT_TYPE]List"
"[COMPONENT_TYPE]List" --> BuilderListComponentCommand : formatted/filtered list of desired components
deactivate "[COMPONENT_TYPE]List"

BuilderListComponentCommand --> BigPP : formatted list
deactivate BuilderListComponentCommand

BigPP --> User : formatted list
deactivate BigPP
deactivate User

@enduml