@startuml
skinparam classAttributeIconSize 0

class "<u>:BigPP</u>" as BigPP
class "<u>:UI</u>" as UI
class "<u>:Parser</u>" as Parser
class "<u>:Command</u>" as Command
' class "<u>:BuilderEditNameCommand</u>" as BuilderEditNameCommand
class "<u>:ViewerAddCommand</u>" as ViewerAddCommand 

class BigPP {
    +main

    -runLoopUntilExit()
    +run()
}

class UI {
    -uiState:UIState

    +getInput()
    +updateUI()
    +showResult()
}

class Parser {

    -parseViewerCommand()
    -parseBuilderCommand()
    +parseCommand()
}

class Command {

    +executeCommand()
}

' class BuilderEditNameCommand {

'     +executeCommand()
' }

class ViewerAddCommand {

    +executeCommand()
}

BigPP -- UI
BigPP -- Parser
' Parser -- BuilderEditNameCommand
Parser -- ViewerAddCommand
' Command <|-right- BuilderEditNameCommand
Command <|-right- ViewerAddCommand

hide circle

@enduml