@startuml


class ComponentList<T> {
    +getListString(componentIndexes: ArrayList<Integer>, getDetails: Boolean): String
    +filterByEfficiencyPsu(...)
    +filterByPowerPsu(...)
    +filterByPowerStorage(...)
    +filterBySizeStorage(...)
    +filterByTypeStorage(...)
    +filterByPowerRam(...)
    +filterBySpeed(...)
    +filterBySticks(...)
    +filterByMemory(...)
    +filterByPowerMotherboard(...)
    +filterBySocketMotherboard(...)
    +filterByFormFactorMotherboard(...)
    +filterByPowerGpu(...)
    +filterByFormFactorGpu(...)
    +filterByPowerCpuCooler(...)
    +filterByNoise(...)
    + filterByRpm(...)               
    + filterBySocketCpu(...)             
    + filterByPowerCpu(...)          
    + filterByBoostClock(...)    
    + filterByBaseClock(...)    
    + filterByThread(...)                  
    + filterByCore(...)                     
    + filterByFormFactorChassis(...) 
    + filterByName(...)                  
    + filterByBrand(...)                 
    + filterByPrice(...)
}



class ChassisList
class CPUList
class CPUCoolerList
class GPUList
class MotherboardList
class PSUList
class RAMList
class StorageList

ChassisList --|> ComponentList
CPUList --|> ComponentList
CPUCoolerList --|> ComponentList
GPUList --|> ComponentList
MotherboardList --|> ComponentList
PSUList --|> ComponentList
RAMList --|> ComponentList
StorageList --|> ComponentList


class PCList {
    -isFilter: Boolean
    -priceFrom: String
    -priceTo: String
    -name: String
    -built: String
    +printPcList()
    +printAltPcList()
    +getIsFilter(): Boolean
    +getIsBuilt(): String
    +getName(): String
    +getPriceFrom(): String
    +getPriceTo(): String
    +setFilterTrue()
    +setFilterFalse()
    +setBuilt(String)
    +setName(String)
    +setPriceFrom(String)
    +setPriceTo(String)
    +filterByPrice(...)
    +filterByName(...)
    +filterByBuilt(...)
}


              
             


class DataStorage {
    - CHASSIS_PATH: String
    - CPU_PATH: String
    - CPU_COOLER_PATH: String
    - GPU_PATH: String
    - MOTHERBOARD_PATH: String
    - PSU_PATH: String
    - RAM_PATH: String
    - STORAGE_PATH: String
    - PREBUILT_PATH: String
    - USER_PATH: String
    - GSON: Gson
    - stringToComponentListMap: Map<String, ComponentList<?>>
    - pcList: PCList
    + saveUserPcs(): void
    + loadAll(): void
    + initStringToComponentListMap(): void
    + loadChassis(path: String): void
    + loadCPU(path: String): void
    + loadCPUCooler(path: String): void
    + loadGPU(path: String): void
    + loadMotherboard(path: String): void
    + loadPSU(path: String): void
    + loadRAM(path: String): void
    + loadStorage(path: String): void
    + loadUserPcs(path: String): void
    + loadPrebuiltPcs(path: String): void
}


DataStorage --> ChassisList
DataStorage --> CPUList
DataStorage --> CPUCoolerList
DataStorage --> GPUList
DataStorage --> MotherboardList
DataStorage --> PSUList
DataStorage --> RAMList
DataStorage --> StorageList
DataStorage --> PCList

@enduml