@startuml
title ViewerAddCommand.executeCommand() Sequence Diagram

participant ":Parser" as Parser
participant ":ViewerAddCommand" as ViewerAddCommand
participant ":PC" as PC
participant ":DataStorage.pcList" as DataStorage.pcList

activate Parser
opt "add <name>"
Parser -> ViewerAddCommand: ViewerAddCommand(String arguments)
activate ViewerAddCommand
ViewerAddCommand -> ViewerAddCommand: getArguments()
activate ViewerAddCommand
alt != ""
    ViewerAddCommand -> PC: PC(name, false)
    activate PC
    PC -> DataStorage.pcList: add(PC)
    activate DataStorage.pcList
    DataStorage.pcList --> PC
    deactivate DataStorage.pcList
    PC --> ViewerAddCommand
    deactivate PC
    deactivate ViewerAddCommand
    ViewerAddCommand --> Parser: return success message
else else
    ViewerAddCommand --> Parser: throw PPException with error message
end

deactivate ViewerAddCommand
end
@enduml